# Automatically generated by pb2py
import protobuf as p


class Address(p.MessageType):
    FIELDS = {
        1: ('address', p.UnicodeType, 0),  # required
    }
    MESSAGE_WIRE_TYPE = 30

    def __init__(
        self,
        address: str = None,
        **kwargs
    ) -> None:
        self.address = address
        super().__init__(**kwargs)
