# Automatically generated by pb2py
import protobuf as p


class CosiCommitment(p.MessageType):
    FIELDS = {
        1: ('commitment', p.BytesType, 0),
        2: ('pubkey', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 72

    def __init__(
        self,
        commitment: bytes = None,
        pubkey: bytes = None,
        **kwargs
    ) -> None:
        self.commitment = commitment
        self.pubkey = pubkey
        super().__init__(**kwargs)
