# Automatically generated by pb2py
import protobuf as p


class DebugLinkMemory(p.MessageType):
    FIELDS = {
        1: ('memory', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 111

    def __init__(
        self,
        memory: bytes = None,
        **kwargs
    ) -> None:
        self.memory = memory
        super().__init__(**kwargs)
