# Automatically generated by pb2py
import protobuf as p


class DebugLinkFlashErase(p.MessageType):
    FIELDS = {
        1: ('sector', p.UVarintType, 0),
    }
    MESSAGE_WIRE_TYPE = 113

    def __init__(
        self,
        sector: int = None,
        **kwargs
    ) -> None:
        self.sector = sector
        super().__init__(**kwargs)
