# Automatically generated by pb2py
import protobuf as p


class DebugLinkStop(p.MessageType):
    MESSAGE_WIRE_TYPE = 103

    def __init__(
        self,
        **kwargs
    ) -> None:
        super().__init__(**kwargs)
