# Automatically generated by pb2py
import protobuf as p


class DebugLinkGetState(p.MessageType):
    MESSAGE_WIRE_TYPE = 101

    def __init__(
        self,
        **kwargs
    ) -> None:
        super().__init__(**kwargs)
