# Automatically generated by pb2py
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None


class DecryptMessage(p.MessageType):
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('nonce', p.BytesType, 0),
        3: ('message', p.BytesType, 0),
        4: ('hmac', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 51

    def __init__(
        self,
        address_n: List[int] = None,
        nonce: bytes = None,
        message: bytes = None,
        hmac: bytes = None,
        **kwargs
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.nonce = nonce
        self.message = message
        self.hmac = hmac
        super().__init__(**kwargs)
