# Automatically generated by pb2py
import protobuf as p


class ECDHSessionKey(p.MessageType):
    FIELDS = {
        1: ('session_key', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 62

    def __init__(
        self,
        session_key: bytes = None,
        **kwargs
    ) -> None:
        self.session_key = session_key
        super().__init__(**kwargs)
