# Automatically generated by pb2py
import protobuf as p


class EncryptedMessage(p.MessageType):
    FIELDS = {
        1: ('nonce', p.BytesType, 0),
        2: ('message', p.BytesType, 0),
        3: ('hmac', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 50

    def __init__(
        self,
        nonce: bytes = None,
        message: bytes = None,
        hmac: bytes = None,
        **kwargs
    ) -> None:
        self.nonce = nonce
        self.message = message
        self.hmac = hmac
        super().__init__(**kwargs)
