# Automatically generated by pb2py
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None


class EthereumGetAddress(p.MessageType):
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('show_display', p.BoolType, 0),
    }
    MESSAGE_WIRE_TYPE = 56

    def __init__(
        self,
        address_n: List[int] = None,
        show_display: bool = None,
        **kwargs
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.show_display = show_display
        super().__init__(**kwargs)
