# Automatically generated by pb2py
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None


class EthereumSignMessage(p.MessageType):
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('message', p.BytesType, 0),  # required
    }
    MESSAGE_WIRE_TYPE = 64

    def __init__(
        self,
        address_n: List[int] = None,
        message: bytes = None,
        **kwargs
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.message = message
        super().__init__(**kwargs)
