# Automatically generated by pb2py
import protobuf as p


class EthereumAddress(p.MessageType):
    FIELDS = {
        1: ('address', p.BytesType, 0),  # required
    }
    MESSAGE_WIRE_TYPE = 57

    def __init__(
        self,
        address: bytes = None,
        **kwargs
    ) -> None:
        self.address = address
        super().__init__(**kwargs)
