# Automatically generated by pb2py
import protobuf as p


class EthereumMessageSignature(p.MessageType):
    FIELDS = {
        1: ('address', p.BytesType, 0),
        2: ('signature', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 66

    def __init__(
        self,
        address: bytes = None,
        signature: bytes = None,
        **kwargs
    ) -> None:
        self.address = address
        self.signature = signature
        super().__init__(**kwargs)
