# Automatically generated by pb2py
import protobuf as p


class EthereumTxAck(p.MessageType):
    FIELDS = {
        1: ('data_chunk', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 60

    def __init__(
        self,
        data_chunk: bytes = None,
        **kwargs
    ) -> None:
        self.data_chunk = data_chunk
        super().__init__(**kwargs)
