# Automatically generated by pb2py
import protobuf as p


class FirmwareErase(p.MessageType):
    FIELDS = {
        1: ('length', p.UVarintType, 0),
    }
    MESSAGE_WIRE_TYPE = 6

    def __init__(
        self,
        length: int = None,
        **kwargs
    ) -> None:
        self.length = length
        super().__init__(**kwargs)
