# Automatically generated by pb2py
# fmt: off
import protobuf as p


class HyconSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 703

    def __init__(
        self,
        signature: str = None,
        recovery: int = None,
        txhash: str = None,
    ) -> None:
        self.signature = signature
        self.recovery = recovery
        self.txhash = txhash

    @classmethod
    def get_fields(cls):
        return {
            1: ('signature', p.UnicodeType, 0),
            2: ('recovery', p.UVarintType, 0),
            3: ('txhash', p.UnicodeType, 0),
        }
