# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class HyconSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 702

    def __init__(
        self,
        address_n: List[int] = None,
        to: str = None,
        amount: str = None,
        fee: str = None,
        nonce: int = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.to = to
        self.amount = amount
        self.fee = fee
        self.nonce = nonce

    @classmethod
    def get_fields(cls):
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('to', p.UnicodeType, 0),
            3: ('amount', p.UnicodeType, 0),
            4: ('fee', p.UnicodeType, 0),
            5: ('nonce', p.UVarintType, 0),
        }
