# Automatically generated by pb2py
import protobuf as p


class Initialize(p.MessageType):
    FIELDS = {
        1: ('state', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 0

    def __init__(
        self,
        state: bytes = None,
        **kwargs
    ) -> None:
        self.state = state
        super().__init__(**kwargs)
