# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .KinAssetType import KinAssetType


class KinChangeTrustOp(p.MessageType):
    MESSAGE_WIRE_TYPE = 810

    def __init__(
        self,
        source_account: str = None,
        asset: KinAssetType = None,
        limit: int = None,
    ) -> None:
        self.source_account = source_account
        self.asset = asset
        self.limit = limit

    @classmethod
    def get_fields(cls):
        return {
            1: ('source_account', p.UnicodeType, 0),
            2: ('asset', KinAssetType, 0),
            3: ('limit', p.UVarintType, 0),
        }
