# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .KinAssetType import KinAssetType


class KinPaymentOp(p.MessageType):
    MESSAGE_WIRE_TYPE = 805

    def __init__(
        self,
        source_account: str = None,
        destination_account: str = None,
        asset: KinAssetType = None,
        amount: int = None,
    ) -> None:
        self.source_account = source_account
        self.destination_account = destination_account
        self.asset = asset
        self.amount = amount

    @classmethod
    def get_fields(cls):
        return {
            1: ('source_account', p.UnicodeType, 0),
            2: ('destination_account', p.UnicodeType, 0),
            3: ('asset', KinAssetType, 0),
            4: ('amount', p.SVarintType, 0),
        }
