# Automatically generated by pb2py
# fmt: off
import protobuf as p


class OnegramSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 603

    def __init__(
        self,
        signature: bytes = None,
        tx_hash: str = None,
    ) -> None:
        self.signature = signature
        self.tx_hash = tx_hash

    @classmethod
    def get_fields(cls):
        return {
            1: ('signature', p.BytesType, 0),
            2: ('tx_hash', p.UnicodeType, 0),
        }
