# Automatically generated by pb2py
# fmt: off
import protobuf as p


class OnegramTxHeader(p.MessageType):

    def __init__(
        self,
        ref_block_num: int = None,
        ref_block_prefix: int = None,
        expiration: int = None,
    ) -> None:
        self.ref_block_num = ref_block_num
        self.ref_block_prefix = ref_block_prefix
        self.expiration = expiration

    @classmethod
    def get_fields(cls):
        return {
            1: ('ref_block_num', p.UVarintType, 0),
            2: ('ref_block_prefix', p.UVarintType, 0),
            3: ('expiration', p.UVarintType, 0),
        }
