# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .OnegramAsset import OnegramAsset
from .OnegramTxHeader import OnegramTxHeader

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class OnegramSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 602

    def __init__(
        self,
        address_n: List[int] = None,
        chain_id: bytes = None,
        header: OnegramTxHeader = None,
        fee: OnegramAsset = None,
        source: str = None,
        destination: str = None,
        amount: OnegramAsset = None,
        memo: str = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.chain_id = chain_id
        self.header = header
        self.fee = fee
        self.source = source
        self.destination = destination
        self.amount = amount
        self.memo = memo

    @classmethod
    def get_fields(cls):
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('chain_id', p.BytesType, 0),
            3: ('header', OnegramTxHeader, 0),
            4: ('fee', OnegramAsset, 0),
            5: ('source', p.UnicodeType, 0),
            6: ('destination', p.UnicodeType, 0),
            7: ('amount', OnegramAsset, 0),
            8: ('memo', p.UnicodeType, 0),
        }
