# Automatically generated by pb2py
# fmt: off
import protobuf as p


class OnegramTxHeader(p.MessageType):

    def __init__(
        self,
        head_block_number: int = None,
        head_block_id: bytes = None,
        expiration: int = None,
    ) -> None:
        self.head_block_number = head_block_number
        self.head_block_id = head_block_id
        self.expiration = expiration

    @classmethod
    def get_fields(cls):
        return {
            1: ('head_block_number', p.UVarintType, 0),
            2: ('head_block_id', p.BytesType, 0),
            3: ('expiration', p.UVarintType, 0),
        }
