# Automatically generated by pb2py
import protobuf as p


class Success(p.MessageType):
    FIELDS = {
        1: ('message', p.UnicodeType, 0),
    }
    MESSAGE_WIRE_TYPE = 2

    def __init__(
        self,
        message: str = None,
        **kwargs
    ) -> None:
        self.message = message
        super().__init__(**kwargs)
