# Automatically generated by pb2py
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None


class TezosSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 152
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('operation_bytes', p.BytesType, 0),
        3: ('to', p.UnicodeType, 0),
        4: ('value', p.UVarintType, 0),
        5: ('fee', p.UVarintType, 0),
    }

    def __init__(
        self,
        address_n: List[int] = None,
        operation_bytes: bytes = None,
        to: str = None,
        value: int = None,
        fee: int = None
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.operation_bytes = operation_bytes
        self.to = to
        self.value = value
        self.fee = fee
