# Automatically generated by pb2py
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None
from .MultisigRedeemScriptType import MultisigRedeemScriptType


class TxOutputType(p.MessageType):
    FIELDS = {
        1: ('address', p.UnicodeType, 0),
        2: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        3: ('amount', p.UVarintType, 0),  # required
        4: ('script_type', p.UVarintType, 0),  # required
        5: ('multisig', MultisigRedeemScriptType, 0),
        6: ('op_return_data', p.BytesType, 0),
        7: ('decred_script_version', p.UVarintType, 0),
    }

    def __init__(
        self,
        address: str = None,
        address_n: List[int] = None,
        amount: int = None,
        script_type: int = None,
        multisig: MultisigRedeemScriptType = None,
        op_return_data: bytes = None,
        decred_script_version: int = None,
        block_hash: bytes = None,
        block_height: bytes = None,
        **kwargs,
    ):
        default_block_hash = b'\x54\x52\xf0\x3c\x7a\xf4\x6d\xf1\x58\xf6\xa6\xfe\x2f\xe9\x49\x49\x66\xed\xc7\x43\x40\x27\xaf\x26\x51\xa3\x88\x0e\x00\x00\x00\x00'  #Zencash 
        default_block_height = b'\x4E\x59\x04' #Zencash
        self.address = address
        self.address_n = address_n if address_n is not None else []
        self.amount = amount
        self.script_type = script_type
        self.multisig = multisig
        self.op_return_data = op_return_data
        self.decred_script_version = decred_script_version
        self.block_hash = default_block_hash if block_hash is None else block_hash
        self.block_height = default_block_height if block_height is None else block_height
        p.MessageType.__init__(self, **kwargs)
