# Automatically generated by pb2py
import protobuf as p


class WordRequest(p.MessageType):
    FIELDS = {
        1: ('type', p.UVarintType, 0),
    }
    MESSAGE_WIRE_TYPE = 46

    def __init__(
        self,
        type: int = None,
        **kwargs
    ) -> None:
        self.type = type
        super().__init__(**kwargs)
